name: CI/CD con Condiciones

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Desplegar en producción si es un push a main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Desplegando en producción..."
          # Agrega aquí tus comandos de despliegue

      - name: Notificar en Slack si el push fue realizado por un usuario
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        run: |
          echo "Notificando en Slack..."
          # Agrega aquí tus comandos para enviar notificaciones a Slack
