name: hola-mundo
#Optional run-name: !HOLA SOY UNA PRUEBA!
on: [push] # Triggers:https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#about-events-that-trigger-workflows
jobs:
  hola-mundo: #Can't contain spaces
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup v3.10
        uses: actions/setup-python@v4 #https://github.com/marketplace/actions/setup-python
        with:
          python-version: "3.10"

      - name: Run Script
        run: |
          python3 main.py
