name: hola-mundo
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup v3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run Script
        run: |
          python3 main.py
